name: "Bundle Analysis"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:      
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the code
        run: bun run build

      - name: Get main branch bundle sizes
        id: main_sizes
        run: |
          echo "bundle_size=$(du -sk ./dist | cut -f1)" >> $GITHUB_ENV
      - name: Clean up
        run: rm -rf node_modules/ dist/

      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: bun install

      - name: Build the code
        run: bun run build

      - name: Get PR branch bundle sizes
        id: pr_sizes
        run: |
          echo "pr_bundle_size=$(du -sk ./dist | cut -f1)" >> $GITHUB_ENV
      - name: Compute size differences
        id: size_diffs
        run: |
          echo "client_diff=$((${{ env.pr_bundle_size }} - ${{ env.bundle_size }}))" >> $GITHUB_ENV
      - name: Comment PR
        uses: mshick/add-pr-comment@v2
        with:
          message-id: "bundle-size-comparison"
          message: |
            ðŸ“¦ Main Branch Bundle Size: ${{ env.bundle_size }} KB
            ðŸš€ PR Branch Bundle Size: ${{ env.pr_bundle_size }} KB
            Î” Client Size Difference: ${{ env.client_diff }} KB
          repo-token: "${{ github.token }}"
